####################
#       PATHS      #
####################

included:
  - Package.swift
  - Plugins

####################
#   RULES STATE    #
####################

opt_in_rules:
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - enum_case_associated_values_count
  - extension_access_modifier
  - empty_string
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - reduce_into
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - toggle_bool
  - unavailable_function
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

####################
#   RULES CONFIG   #
####################

### Idiomatic ###
type_name:
  excluded:
    - C

### Metrics ###
closure_body_length:
  warning: 25
file_length:
  warning: 300
  ignore_comment_only_lines: true
line_length:
  ignores_comments: true
  ignores_urls: true
nesting:
  type_level: 2

### Style ###
opening_brace:
  allow_multiline_func: true
trailing_whitespace:
  ignores_empty_lines: true
