name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches-ignore:
      - 'bugfix/**'
      - 'feature/**'
      - 'topic/**'
    paths-ignore:
      - '.gitignore'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: macos-15

    steps:
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint Swift Code
        run: swiftlint lint --strict --reporter github-actions-logging

  dependencies:
    name: Dependencies
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.4.app/Contents/Developer"

    steps:
      - name: Runner Overview
        run: system_profiler SPHardwareDataType SPSoftwareDataType SPDeveloperToolsDataType

      - name: Checkout
        uses: actions/checkout@v5

      - name: Resolve Package Dependencies
        run: swift package resolve -v
